/* #human-slop
 * https://github.com/huydo862003/Fck-AI-Slop/edit/main/README.md
 */

import {
  PhArrowDown,
  PhArrowFatLinesUp,
  PhArrowFatUp,
  PhArrowLeft,
  PhArrowRight,
  PhArrowSquareOut,
  PhArrowUp,
  PhArrowsIn,
  PhArrowsLeftRight,
  PhArrowsOut,
  PhArticle,
  PhBackspace,
  PhBell,
  PhBook,
  PhBookOpen,
  PhBrain,
  PhCalendar,
  PhCards,
  PhCaretDoubleDown,
  PhCaretDoubleUp,
  PhCaretDown,
  PhCaretLeft,
  PhCaretRight,
  PhCaretUp,
  PhChartBar,
  PhChat,
  PhCheck,
  PhCheckCircle,
  PhClipboard,
  PhClock,
  PhCode,
  PhCommand,
  PhCopy,
  PhCrosshair,
  PhDatabase,
  PhDotsSixVertical,
  PhDotsThree,
  PhDotsThreeVertical,
  PhDownloadSimple,
  PhEnvelope,
  PhEye,
  PhEyeSlash,
  PhFile,
  PhFlag,
  PhFolder,
  PhFrameCorners,
  PhFunnel,
  PhGear,
  PhGithubLogo,
  PhGlobe,
  PhGraph,
  PhGridFour,
  PhHeart,
  PhHouse,
  PhImage,
  PhInfo,
  PhKeyReturn,
  PhLightning,
  PhLink,
  PhList,
  PhLock,
  PhLockOpen,
  PhMagicWand,
  PhMagnifyingGlass,
  PhMapPinSimple,
  PhMinus,
  PhMoon,
  PhNewspaper,
  PhOption,
  PhPackage,
  PhPaperPlaneTilt,
  PhPause,
  PhPencil,
  PhPencilSimple,
  PhPlay,
  PhPlayCircle,
  PhPlus,
  PhQuestion,
  PhReadCvLogo,
  PhRss,
  PhShareNetwork,
  PhSignIn,
  PhSignOut,
  PhSliders,
  PhSortAscending,
  PhSpinner,
  PhStar,
  PhStop,
  PhSun,
  PhTag,
  PhTerminal,
  PhTrash,
  PhTreeStructure,
  PhUploadSimple,
  PhUser,
  PhUsers,
  PhWarning,
  PhWarningCircle,
  PhWindowsLogo,
  PhX,
  PhXCircle,
} from '@phosphor-icons/vue';
import type {
  Component,
} from 'vue';

export enum GIconName {
  // Navigation
  Home = 'home',
  ArrowLeft = 'arrow-left',
  ArrowRight = 'arrow-right',
  ArrowUp = 'arrow-up',
  ArrowDown = 'arrow-down',
  ArrowsLeftRight = 'arrows-left-right',
  ChevronLeft = 'chevron-left',
  ChevronRight = 'chevron-right',
  ChevronUp = 'chevron-up',
  ChevronDown = 'chevron-down',
  CaretDoubleUp = 'caret-double-up',
  CaretDoubleDown = 'caret-double-down',
  MapPin = 'map-pin',
  Crosshair = 'crosshair',

  // Actions
  Plus = 'plus',
  Minus = 'minus',
  X = 'x',
  Check = 'check',
  Copy = 'copy',
  Trash = 'trash',
  Pencil = 'pencil',
  Download = 'download',
  Upload = 'upload',
  Share = 'share',
  Link = 'link',
  ExternalLink = 'external-link',
  PencilSimple = 'pencil-simple',
  FrameCorners = 'frame-corners',

  // UI
  Search = 'search',
  Filter = 'filter',
  Sort = 'sort',
  Menu = 'menu',
  Grip = 'grip',
  VEllipsis = 'v-ellipsis',
  HEllipsis = 'h-ellipsis',
  Gear = 'gear',
  Sliders = 'sliders',
  Eye = 'eye',
  EyeSlash = 'eye-slash',
  Expand = 'expand',
  Collapse = 'collapse',

  // Status
  Info = 'info',
  Warning = 'warning',
  WarningCircle = 'warning-circle',
  CheckCircle = 'check-circle',
  XCircle = 'x-circle',
  Question = 'question',
  Bell = 'bell',
  Spinner = 'spinner',

  // Content
  File = 'file',
  Folder = 'folder',
  Image = 'image',
  Code = 'code',
  Database = 'database',
  Terminal = 'terminal',
  Article = 'article',
  Book = 'book',
  BookOpen = 'book-open',
  Tag = 'tag',
  Flag = 'flag',
  Newspaper = 'newspaper',
  Rss = 'rss',
  ReadCvLogo = 'read-cv-logo',
  Package = 'package',

  // Communication
  Chat = 'chat',
  Envelope = 'envelope',
  PaperPlane = 'paper-plane',

  // User
  User = 'user',
  Users = 'users',
  SignIn = 'sign-in',
  SignOut = 'sign-out',

  // Media
  Play = 'play',
  PlayCircle = 'play-circle',
  Pause = 'pause',
  Stop = 'stop',

  // Brands
  GithubLogo = 'github-logo',

  // Misc
  MagicWand = 'magic-wand',
  Star = 'star',
  Heart = 'heart',
  Lightning = 'lightning',
  TreeStructure = 'tree-structure',
  Moon = 'moon',
  Sun = 'sun',
  Globe = 'globe',
  Calendar = 'calendar',
  Clock = 'clock',
  Lock = 'lock',
  LockOpen = 'lock-open',
  Graph = 'graph',
  ChartBar = 'chart-bar',
  List = 'list',
  Grid = 'grid',
  Clipboard = 'clipboard',
  Brain = 'brain',
  Cards = 'cards',

  // Keyboard
  KeyReturn = 'key-return',
  Backspace = 'backspace',
  Command = 'command',
  Option = 'option',
  WindowsLogo = 'windows-logo',
  ShiftKey = 'shift-key',
  CapsLockKey = 'caps-lock-key',
}

/* Phosphor icon lookup by enum value
 **/
export const iconMap: Record<GIconName, Component> = {
  // Navigation
  [GIconName.Home]: PhHouse,
  [GIconName.ArrowLeft]: PhArrowLeft,
  [GIconName.ArrowRight]: PhArrowRight,
  [GIconName.ArrowUp]: PhArrowUp,
  [GIconName.ArrowDown]: PhArrowDown,
  [GIconName.ArrowsLeftRight]: PhArrowsLeftRight,
  [GIconName.ChevronLeft]: PhCaretLeft,
  [GIconName.ChevronRight]: PhCaretRight,
  [GIconName.ChevronUp]: PhCaretUp,
  [GIconName.ChevronDown]: PhCaretDown,
  [GIconName.CaretDoubleUp]: PhCaretDoubleUp,
  [GIconName.CaretDoubleDown]: PhCaretDoubleDown,
  [GIconName.MapPin]: PhMapPinSimple,
  [GIconName.Crosshair]: PhCrosshair,

  // Actions
  [GIconName.Plus]: PhPlus,
  [GIconName.Minus]: PhMinus,
  [GIconName.X]: PhX,
  [GIconName.Check]: PhCheck,
  [GIconName.Copy]: PhCopy,
  [GIconName.Trash]: PhTrash,
  [GIconName.Pencil]: PhPencil,
  [GIconName.Download]: PhDownloadSimple,
  [GIconName.Upload]: PhUploadSimple,
  [GIconName.Share]: PhShareNetwork,
  [GIconName.Link]: PhLink,
  [GIconName.ExternalLink]: PhArrowSquareOut,
  [GIconName.PencilSimple]: PhPencilSimple,
  [GIconName.FrameCorners]: PhFrameCorners,

  // UI
  [GIconName.Search]: PhMagnifyingGlass,
  [GIconName.Filter]: PhFunnel,
  [GIconName.Sort]: PhSortAscending,
  [GIconName.Menu]: PhList,
  [GIconName.Grip]: PhDotsSixVertical,
  [GIconName.VEllipsis]: PhDotsThreeVertical,
  [GIconName.HEllipsis]: PhDotsThree,
  [GIconName.Gear]: PhGear,
  [GIconName.Sliders]: PhSliders,
  [GIconName.Eye]: PhEye,
  [GIconName.EyeSlash]: PhEyeSlash,
  [GIconName.Expand]: PhArrowsOut,
  [GIconName.Collapse]: PhArrowsIn,

  // Status
  [GIconName.Info]: PhInfo,
  [GIconName.Warning]: PhWarning,
  [GIconName.WarningCircle]: PhWarningCircle,
  [GIconName.CheckCircle]: PhCheckCircle,
  [GIconName.XCircle]: PhXCircle,
  [GIconName.Question]: PhQuestion,
  [GIconName.Bell]: PhBell,
  [GIconName.Spinner]: PhSpinner,

  // Content
  [GIconName.File]: PhFile,
  [GIconName.Folder]: PhFolder,
  [GIconName.Image]: PhImage,
  [GIconName.Code]: PhCode,
  [GIconName.Database]: PhDatabase,
  [GIconName.Terminal]: PhTerminal,
  [GIconName.Article]: PhArticle,
  [GIconName.Book]: PhBook,
  [GIconName.BookOpen]: PhBookOpen,
  [GIconName.Tag]: PhTag,
  [GIconName.Flag]: PhFlag,
  [GIconName.Newspaper]: PhNewspaper,
  [GIconName.Rss]: PhRss,
  [GIconName.ReadCvLogo]: PhReadCvLogo,
  [GIconName.Package]: PhPackage,

  // Communication
  [GIconName.Chat]: PhChat,
  [GIconName.Envelope]: PhEnvelope,
  [GIconName.PaperPlane]: PhPaperPlaneTilt,

  // User
  [GIconName.User]: PhUser,
  [GIconName.Users]: PhUsers,
  [GIconName.SignIn]: PhSignIn,
  [GIconName.SignOut]: PhSignOut,

  // Media
  [GIconName.Play]: PhPlay,
  [GIconName.PlayCircle]: PhPlayCircle,
  [GIconName.Pause]: PhPause,
  [GIconName.Stop]: PhStop,

  // Brands
  [GIconName.GithubLogo]: PhGithubLogo,

  // Misc
  [GIconName.MagicWand]: PhMagicWand,
  [GIconName.Star]: PhStar,
  [GIconName.Heart]: PhHeart,
  [GIconName.Lightning]: PhLightning,
  [GIconName.TreeStructure]: PhTreeStructure,
  [GIconName.Moon]: PhMoon,
  [GIconName.Sun]: PhSun,
  [GIconName.Globe]: PhGlobe,
  [GIconName.Calendar]: PhCalendar,
  [GIconName.Clock]: PhClock,
  [GIconName.Lock]: PhLock,
  [GIconName.LockOpen]: PhLockOpen,
  [GIconName.Graph]: PhGraph,
  [GIconName.ChartBar]: PhChartBar,
  [GIconName.List]: PhList,
  [GIconName.Grid]: PhGridFour,
  [GIconName.Clipboard]: PhClipboard,
  [GIconName.Brain]: PhBrain,
  [GIconName.Cards]: PhCards,

  // Keyboard
  [GIconName.KeyReturn]: PhKeyReturn,
  [GIconName.Backspace]: PhBackspace,
  [GIconName.Command]: PhCommand,
  [GIconName.Option]: PhOption,
  [GIconName.WindowsLogo]: PhWindowsLogo,
  [GIconName.ShiftKey]: PhArrowFatUp,
  [GIconName.CapsLockKey]: PhArrowFatLinesUp,
};
